const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
const FETCH_PEOPLE_ERROR = 'FETCH_PEOPLE_ERROR';
const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
const FETCH_PERSON_ERROR = 'FETCH_PERSON_ERROR';

const LOCATION_CHANGE = 'LOCATION_CHANGE';

export {
  FETCH_PEOPLE_SUCCESS,
  FETCH_PEOPLE_ERROR,
  FETCH_PERSON_SUCCESS,
  FETCH_PERSON_ERROR,
  LOCATION_CHANGE
};
